version: '3.8'

services:
  postgresql_db_book_example:
    image: postgres:16.4
    container_name: postgresql_db_book_example
    restart: unless-stopped
    environment:      
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Test2024!
      - POSTGRES_DB=BooksExample
    ports: 
      - "5432:5432"